# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Ted Carstensen
description: A personal site for Ted Carstensen
baseurl: ""
url: https://tedcarstensen.com

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Ted Carstensen
  description: howdy, i'm ted, it's nice to meet you. come say hello at any of the links below.
  # cv: assets/cv.pdf
  # address:
  #   - University of Jekyll
  #   - Department of Themes
  #   - 123 Main St, Anytown, USA
  contact:
  #   office: Foobar Hall 1.23
  #   phone: +1 234 567 890
  email: ted at tedcarstensen.com
  # demo: https://hacked-jekyll.netlify.app
  # source: https://github.com/piazzai/hacked-jekyll
  profiles:
    mastodon: https://www.tedcarstensen.social
    linkedin: https://www.linkedin.com/in/tedcarstensen/
    github: https://github.com/tedcarstensen
    heavybit: https://www.heavybit.com/team/ted-carstensen

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never
